[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_BASE_URL = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
